Param(
  [String]$Bucket,
  [String]$UploadPath = '.\upload\aws-serverless-workshops-master\WebApplication\1_StaticWebHosting\website'
)

$eol = "`r`n"
$tab = "`t"
$counter = 1

if(Get-Item -Path ".\UploadBucketFiles.tf" -ErrorAction SilentlyContinue) {
  Remove-Item -Path ".\UploadBucketFiles.tf" -Confirm:$false -ErrorAction SilentlyContinue -Force
}

#windows sucks with mime types so i made a csv with the most common ones
$mimetypes = Import-CSV -Path ./scripts/filemimetypes.csv

#Sets location to #uploadpath, otherwise the $file output has the full path
Push-Location $UploadPath

$files = (Get-ChildItem -Recurse -File)

#Generate message at the top of the tf file"
$output+= '/*' + $eol
$output+= 'Do not modify this file' + $eol
$output+= 'It is automatically generated by ./scripts/CreateBucketUploadFile.ps1' + $eol
$output+= 'Re-Run terraform init & apply once file is generated' + $eol
$output+= '*/' + $eol
$output+= $eol

Foreach ($file in $files) {
    $filename = ($file.FullName | Resolve-Path -Relative).Replace(".\","").Replace("\","/")
    $filetype = $file.Extension
    $output+= 'resource "aws_s3_bucket_object" "file_' + $counter++ + '" {' + $eol
    $output+= $tab + 'bucket = "' + $Bucket + '"' + $eol
    $output+= $tab + 'key = "' + $filename + '"' + $eol
    $output+= $tab + 'source = "' + $UploadPath.Replace("\","/") + '/' + $filename + '"' + $eol
    $output+= $tab + 'content_type = "' + $mimetypes.Where({$PSItem.File -eq $filetype }).mime + '"' + $eol
    $output+= '}' + $eol
    $output+= $eol 
}

#switch back to path where script ran from by main tf file
Pop-Location

#dump out the contents to tf file
$output | Out-File -FilePath ".\uploadbucketfiles.tf" -Encoding Default -append